// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab05.Models;

public partial class Account
{
    public string Username { get; set; }

    public int? Makh { get; set; }

    public string Password { get; set; }

    public virtual Khachhang MakhNavigation { get; set; }
}