// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab05.Models;

public partial class Cthd
{
    public int Mahd { get; set; }

    public int Mama { get; set; }

    public string Mak { get; set; }

    public int SL { get; set; }

    public virtual Hoadon MahdNavigation { get; set; }

    public virtual Monan MamaNavigation { get; set; }
}