// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab05.Models;

public partial class Hoadon
{
    public int Mahd { get; set; }

    public int? Makh { get; set; }

    public double Tht { get; set; }

    public DateTime Ngayhd { get; set; }

    public virtual ICollection<Cthd> Cthds { get; set; } = new List<Cthd>();

    public virtual Khachhang MakhNavigation { get; set; }
}