// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab05.Models;

public partial class Khachhang
{
    public int Makh { get; set; }

    public string Ho { get; set; }

    public string Ten { get; set; }

    public DateOnly? Ngaysinh { get; set; }

    public string Diachi { get; set; }

    public string Sdt { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();

    public virtual ICollection<Hoadon> Hoadons { get; set; } = new List<Hoadon>();
}