// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab05.Models;

public partial class Monan
{
    public int Mama { get; set; }

    public string Tenma { get; set; }

    public double Donggia { get; set; }

    public string Loaima { get; set; }

    public virtual ICollection<Cthd> Cthds { get; set; } = new List<Cthd>();
}